name: highlight_text
description: 一个在flutter上的文本组件，支持以下划线的方式高亮显示内容，支持自定义下划线的高度和偏移量，支持高亮部分换行显示。
version: 0.0.1
homepage: https://github.com/hucong730/highlight_text

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
